### ISSUE TITLE
Hotfix for broken startup sequence functionality in OneIM 9.1

### ISSUE THREAD

**Issue by NielsDeGroot** [nl07427/ServiceNowInterface#7]
The Wiki Installation text states that: In the 9.1 environment we are using for testing is the startup sequence functionality broken
You can now request a hotfix from OneIM support: #36226

**Comment by nl07427** [comment]
Hi Niels,

Thanks for the info, this is important for groups / companies having a support contract. As a open source project we do not have a support contract and access to hotfixes

**Comment by nl07427** [comment]
I will update the Wiki documentation
